# Generated by Django 6.0 on 2026-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitemmodel_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='paymentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('processing', True)), fields=('order',), name='one_processing_payment_per_order'),
        ),
    ]
