# Generated by Django 6.0 on 2026-01-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_status'),
        ('payments', '0002_alter_paymentmodel_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='provider',
            new_name='method',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.ordermodel'),
        ),
    ]
