# Generated by Django 6.0 on 2026-02-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitemmodel_return_info_ordermodel_return_info_and_more'),
        ('payments', '0002_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='refund_info',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('REFUNDED', 'Refunded')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='refunditemmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='refundmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_refunds', to='orders.ordermodel'),
        ),
        migrations.AddConstraint(
            model_name='refunditemmodel',
            constraint=models.UniqueConstraint(fields=('item',), name='unique_refund_per_item'),
        ),
    ]
