# Generated by Django 6.0 on 2026-01-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_provider_paymentmodel_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='provider_signature',
        ),
    ]
