# Generated by Django 6.0 on 2026-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentmodel_refund_info_alter_paymentmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_confirmation',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=100),
        ),
    ]
