# Generated by Django 6.0 on 2026-01-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemmodel_status_alter_ordermodel_status'),
        ('payments', '0004_remove_paymentmodel_provider_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.ordermodel'),
        ),
        migrations.CreateModel(
            name='RefundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=50)),
                ('method', models.CharField(choices=[('COD', 'Cod'), ('RAZORPAY', 'Razorpay')], max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_Refunds', to='orders.ordermodel')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_refunds', to='orders.orderitemmodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds', to='payments.paymentmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_item',), name='unique_refund_per_order_item')],
            },
        ),
    ]
