# Generated by Django 6.0 on 2026-01-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
