# Generated by Django 6.0 on 2026-01-05 10:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_addressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
