# Generated by Django 6.0 on 2026-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('REFUNDED', 'Refunded'), ('RETURNED', 'Returned'), ('RETURN_REQUESTED', 'Return Requested'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
