# Generated by Django 6.0 on 2026-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitemmodel_status_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(choices=[('REFUNDED', 'Refunded'), ('SHIPPED', 'Shipped'), ('CONFIRMED', 'Confirmed'), ('RETURN_REQUESTED', 'Return Requested'), ('PAID', 'Paid'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50),
        ),
    ]
