# Generated by Django 6.0 on 2026-02-01 10:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitemmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='return_info',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('RETURNED', 'Returned')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='return_info',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUESTED', 'Requested'), ('RETURNED', 'Returned')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='ReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=6)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PICKED_UP', 'Picked Up'), ('RECEIVED', 'Received'), ('REFUND_COMPLETED', 'Refund Completed')], default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_returns', to='orders.ordermodel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('PICKED_UP', 'Picked Up'), ('RECEIVED', 'Received'), ('REFUND_COMPLETED', 'Refund Completed')], default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_returns', to='orders.orderitemmodel')),
                ('return_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.returnmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item',), name='unique_return_per_item')],
            },
        ),
    ]
