# Generated by Django 6.0 on 2025-12-30 07:26

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='level',
            field=models.PositiveIntegerField(null=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='lft',
            field=models.PositiveIntegerField(null=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='rght',
            field=models.PositiveIntegerField(null=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, null=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.categorymodel'),
        ),
    ]
