# Generated by Django 6.0 on 2026-01-09 17:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categorymodel_level_alter_categorymodel_lft_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmodel',
            name='unique_product_name_per_brand',
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='brandmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_brand_name'),
        ),
        migrations.AddConstraint(
            model_name='brandmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='unique_slug_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name'),
        ),
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='unique_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('brand'), name='unique_product_name_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='unique_slug_per_product'),
        ),
    ]
